"""empty message

Revision ID: 6d6569780891
Revises: 2b9295e4413b
Create Date: 2024-05-24 17:01:22.294045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6569780891'
down_revision = '2b9295e4413b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Reserved', 'Completed', 'Cancelled', name='reservation_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
