"""empty message

Revision ID: 8cc6d7269b5f
Revises: 6d6569780891
Create Date: 2024-05-25 17:22:22.485088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc6d7269b5f'
down_revision = '6d6569780891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('isActive')
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
