"""empty message

Revision ID: 8e02c9546ca9
Revises: 
Create Date: 2024-03-22 13:54:17.809673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e02c9546ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cust_user_name', sa.String(length=50), nullable=False),
    sa.Column('cust_full_name', sa.String(length=50), nullable=False),
    sa.Column('cust_phone', sa.String(length=50), nullable=False),
    sa.Column('cust_gender', sa.String(length=20), nullable=False),
    sa.Column('cust_rol_name', sa.String(length=20), nullable=False),
    sa.Column('cust_password', sa.String(length=256), nullable=False),
    sa.Column('cust_photo', sa.String(length=256), nullable=True),
    sa.Column('cust_registrationDate', sa.Date(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cust_id'),
    sa.UniqueConstraint('cust_phone'),
    sa.UniqueConstraint('cust_user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
