"""empty message

Revision ID: 92c6848b16b6
Revises: 9900f7cb0171
Create Date: 2024-05-23 12:17:21.766938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c6848b16b6'
down_revision = '9900f7cb0171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.alter_column('table_name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.alter_column('table_name',
               existing_type=sa.String(length=4),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
