"""empty message

Revision ID: 9900f7cb0171
Revises: d519333484bd
Create Date: 2024-05-23 12:15:18.147062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9900f7cb0171'
down_revision = 'd519333484bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_tables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('table_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_tables')
    # ### end Alembic commands ###
