"""empty message

Revision ID: a04d850a11fa
Revises: 
Create Date: 2024-05-23 18:34:47.919685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04d850a11fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('upcoming', sa.Integer(), nullable=True),
    sa.Column('in_progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Reserved', 'Completed', 'Cancelled', name='reservation_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.cust_id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.table_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('time_slots',
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('slot_time_08_am', sa.String(length=10), nullable=True),
    sa.Column('description_08_am', sa.String(length=255), nullable=True),
    sa.Column('slot_time_09_am', sa.String(length=10), nullable=True),
    sa.Column('description_09_am', sa.String(length=255), nullable=True),
    sa.Column('slot_time_10_am', sa.String(length=10), nullable=True),
    sa.Column('description_10_am', sa.String(length=255), nullable=True),
    sa.Column('slot_time_11_am', sa.String(length=10), nullable=True),
    sa.Column('description_11_am', sa.String(length=255), nullable=True),
    sa.Column('slot_time_12_pm', sa.String(length=10), nullable=True),
    sa.Column('description_12_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_01_pm', sa.String(length=10), nullable=True),
    sa.Column('description_01_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_02_pm', sa.String(length=10), nullable=True),
    sa.Column('description_02_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_03_pm', sa.String(length=10), nullable=True),
    sa.Column('description_03_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_04_pm', sa.String(length=10), nullable=True),
    sa.Column('description_04_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_05_pm', sa.String(length=10), nullable=True),
    sa.Column('description_05_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_06_pm', sa.String(length=10), nullable=True),
    sa.Column('description_06_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_07_pm', sa.String(length=10), nullable=True),
    sa.Column('description_07_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_08_pm', sa.String(length=10), nullable=True),
    sa.Column('description_08_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_09_pm', sa.String(length=10), nullable=True),
    sa.Column('description_09_pm', sa.String(length=255), nullable=True),
    sa.Column('slot_time_10_pm', sa.String(length=10), nullable=True),
    sa.Column('description_10_pm', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['table_reservations.reservation_id'], ),
    sa.PrimaryKeyConstraint('time_slot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_slots')
    op.drop_table('table_reservations')
    # ### end Alembic commands ###
