"""empty message

Revision ID: bedbbb42a4d1
Revises: c96a02c3f88d
Create Date: 2024-05-25 20:52:10.337420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedbbb42a4d1'
down_revision = 'c96a02c3f88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_drop_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('cust_drop_address')

    # ### end Alembic commands ###
