"""empty message

Revision ID: c96a02c3f88d
Revises: 8cc6d7269b5f
Create Date: 2024-05-25 17:57:08.583108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96a02c3f88d'
down_revision = '8cc6d7269b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('transaction_no', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['transaction_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transaction_no')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
