"""empty message

Revision ID: f59356b581be
Revises: bedbbb42a4d1
Create Date: 2024-05-25 20:56:14.267395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f59356b581be'
down_revision = 'bedbbb42a4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('cust_drop_address')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_drop_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cust_drop_address')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_drop_address', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
